spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        max-active: 25
        max-wait: 5000
        test-on-borrow: false
        test-while-idle: true
        validation-query: SELECT 1
        initial-size: 20
        default-auto-commit: false
        default-transaction-isolation: 2
        jmx-enabled: false
    jpa:
        hibernate:
            ddl-auto: update
        database: MYSQL
        show-sql: true
server:
    tomcat:
        max-threads: 10
        max-connections: 20

rest-template:
    http-client-connection:
        max-total: 20
        max-per-route: 10
    request-config:
        connection-request-timeout: 3000
        connect-timeout: 3000
        socket-timeout: 3000
    socket-config:
        so-keep-alive: true
        tcp-no-delay: true

---

spring:
    profiles: local
    datasource:
        url: jdbc:mysql://localhost:3306/oneland?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
        username: root
        password:

---

spring:
    profiles: cafe24
    datasource:
        url: jdbc:mysql://localhost:3306/gachadoll?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
        username: gachadoll
        password: daily500

---

spring:
    profiles: production
    datasource:
#        url: jdbc:mysql://localhost:3306/oneland?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
#        username: root
#        password:
        url: jdbc:mysql://localhost:3306/gacha?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&transformedBitIsBoolean=true
        username: gachadoll
        password: daily500

---

spring:
    profiles:
#        active: local
        active: cafe24

